# A docker-compose must always start by the version tag.
# We use '3' because it's the last version at this time.
version: '3'

services:

  mongodb:
    
    image: jaques555/express_mongo_server:db

    container_name: mongodb

    restart: always

    ports:
      - 27017:27017
      
    
  server:

    image: jaques555/express_mongo_server:server
    
    container_name: ExpressServer

    restart: always

    ports:
      - 3000:3000

    links:
      - "mongodb:database"
      
    depends_on:
      - mongodb
